spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: module-a
            uri: http://module-a:8080
            predicates:
              - Path=/api/a,/api/a/**
            filters:
              - SetPath=/
          - id: module-c
            uri: http://module-c:8080
            predicates:
              - Path=/api/c,/api/c/**
            filters:
              - SetPath=/

server:
  port: 8084

# OpenTelemetry via Java agent (OTEL_* env vars in Docker)

# OpenAPI / Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
